### ISSUE TITLE
[Bug]: EngineInPluginDemo_VST3 doesn't compile

### ISSUE THREAD

**Issue by JelleBakker** [Tracktion/tracktion_engine#234]
### Detailed steps on how to reproduce the bug

Build the EngineInPluginDemo_VST3 cmake target on Tracktion develop branch.

I'm pretty sure this is actually a JUCE bug, which has been fixed [last week](https://github.com/juce-framework/JUCE/commit/1798b12d4b49ebf6ae6e76fd73061e2637e93c4b).

In my opinion it would be a good improvement to the Tracktion CI pipeline to build EngineInPluginDemo so that compile errors like these are catched earlier on.

### What is the expected behaviour?

I expect it to compile without errors.

### Operating systems

macOS

### What versions of the operating systems?

Sequoia 15.0

### Architectures

ARM

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by drowaudio** [comment]
So I thought I was compiling all the plugin types but it looks like it was just compiling the main target.

But now I have a problem that because it uses a PIP for the plugin, the config is generated automatically by JUCE and it doesn't create a proper LV2 URI. So the LV2 build breaks when building the `EngineInPluginDemo_All` target so nothing can compile.

There also doesn't seem to be a way to disable LV2 builds or supply a correct URI with a PIP.

So the only fix is to ditch the PIP and make it a proper plugin target which might take a bit of time.

**Comment by JelleBakker** [comment]
I understand, in my cade I don't use LV2 so I'm just stuck with the VST3 issue which I think should be fixed by updating JUCE. 

Speaking about updating JUCE, I was wondering what is the recommended approach for using a custom JUCE version with Tracktion? JUCE is a submodule of tracktion but juceaide is built immediately when I clone Tracktion in CMake using CPM. There is no obvious solution I can use in CMake that will make Tracktion use a different JUCE version. It'd be quite useful if I could somehow point Tracktion to a custom JUCE folder prior to cloning Tracktion. Any suggestions? @drowaudio

**Comment by drowaudio** [comment]
Can you do a `FetchContent` without cloning submodules?

Why is it building anything at that point though? Shouldn't you have to trigger a build from a specific target from your build system?

**Comment by drowaudio** [comment]
Ok, I figured out how to do this and updated juce on develop.
