### ISSUE TITLE
Can't get the plugin demo to show VST3 plugins on linux

### ISSUE THREAD

**Issue by stonepreston** [Tracktion/tracktion_engine#25]
I am trying to use the plugin demo to load a VST3 plugin on linux (ubuntu 20.04). The plugin I am trying to load is the [JUCE Cmake example plugin](https://github.com/juce-framework/JUCE/tree/master/examples/CMake/AudioPlugin). I have tested it and it runs in Reaper as well as the JUCE audio plugin host (I also tried loading it in tracktion waveform but I get an error that the .so file failed to load correctly. The plugin is located at  ~/.vst3/Example.vst3/Contents/x86_64-linux/Example.so. 

How can I get the tracktion engine plugin demo to load this plugin? There doesnt seem to be a way to scan for plugins using the options menu after clicking the plugins button. The plugin list just loads up and is empty. 

Is it even possible for the traction engine to load VST3s on linux? If so how would I got about doing that?

**Comment by CharlesHolbrow** [comment]
Last I checked, VST3 is not supported on Linux. This is actually a limitation of JUCE v5. 

Since Steinberg stopped giving developers access to the VST2 SDK, this does mean that there's no way to compile VSTs on Linux and then use them in Tracktion Engine -- unless you can track down the VST2 SDK. Some users have managed to sweet talk Steinberg into giving them access.

Hopefully, Tracktion Engine will update to JUCE v6 so we can access VST3 plugins too.

**Comment by stonepreston** [comment]
@CharlesHolbrow  the dev branch of tracktion engine uses juce 6

**Comment by stonepreston** [comment]
I just tried it in ubuntu 18.04 and its working. Not sure what is different. Its possible I wasnt on the dev branch in my tracktion git submodule but I believe it was set up to track dev.
