### ISSUE TITLE
Generate examples script fails to build 

### ISSUE THREAD

**Issue by ianacaburian** [Tracktion/tracktion_engine#46]
Hi there,

Getting a build error when trying to run the generate_examples script:
`CompileC build/Projucer.build/Release/Projucer\ -\ App.build/Objects-normal/arm64/include_juce_core.o /Users/username/Dev/Tracktion/tracktion_engine/modules/juce/extras/Projucer/JuceLibraryCode/include_juce_core.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)`

I'm on macOS 11.1 with Xcode Version 12.3 (12C33)

Thanks for your help.

**Comment by drowaudio** [comment]
What's the actual error message here?
It looks like it's failing to build JUCE when building the Projucer. We might need to update JUCE in the Engine submodule.

**Comment by drowaudio** [comment]
Also, can I check what branch you're trying to build?

**Comment by ianacaburian** [comment]
Is this what you're looking for ? 
`
** BUILD FAILED **


The following build commands failed:
	CompileC build/Projucer.build/Release/Projucer\ -\ App.build/Objects-normal/arm64/include_juce_events.o /Users/username/Dev/Tracktion/tracktion_engine/modules/juce/extras/Projucer/JuceLibraryCode/include_juce_events.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
username@users-iMac mac % git branch
* master`

**Comment by drowaudio** [comment]
I think JUCE needs to be updated to build the ARM version of PJ.
If you `cd` in to the `module/juce` directory and pull in the tip of JUCE then re-run the `generate_examples` script it should work. We'll update JUCE in the repo shortly.
___
Alternatively, if you switch to the `tracktion_engine` branch, that is using a more recent version of JUCE so that should already work.

**Comment by ianacaburian** [comment]
No worries, thanks for your help.
