### ISSUE TITLE
PlaybackDemo example issue

### ISSUE THREAD

**Issue by cassanelligiovanni** [Tracktion/tracktion_engine#7]
Don't know if it is the right place to make this question, but when I try to compile PlaybackDemo example with Xcode for Mac,  I get following error : JUCE Assertion failure in PlaybackDemo.h:41, all the other example are working fine

**Comment by teotigraphix** [comment]
Try the develop branch, they fixed this I am pretty sure.

**Comment by drowaudio** [comment]
This is probably because you haven't passed it a path to an Edit file?
In order to keep this example as simple as possible, the file to play back is passed as the first command line parameter. This assertion is telling you that this is missing.

If you're looking for a file to play, try grabbing the W9 demo from tracktion.com and creating a MIDI only Edit (audio files are handled differently in Waveform so aren't currently readable by the PlaybackDemo).

We'll be improving this example soon but it might be a good idea to focus on the StepSequencerDemo or PitchAndTimeDemo for now.
